name: Docker Image CI

on:
  push:
    branches: [ master, feature/ci ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chrislrx/ovpnproxy:$(date +%s)
    - name: Push the Docker image
      run: docker push chrislrx/ovpnproxy:$(date +%s)
